package observers;

import interfaces.Observer;

/**
 * The PrintLowercase class handles
 * printing the lowercase letter value
 * of the number generated by the
 * NumberGenerator class.
 *
 * @author Waswa Olunga
 */

public class PrintLowercase implements Observer {

	private static final int DIFFERENCE_FROM_UPPERCASE_TO_LOWERCASE = 32;


	@Override
	public void stateChanged(int num) {
		System.out.println(Character.toString((char) (num + DIFFERENCE_FROM_UPPERCASE_TO_LOWERCASE)));
	}
}